#!/bin/sh

# Erase backup files older than 62 days
# -------------------------


myFolder[0]='ken1'
myFolder[1]='ken2'
myFolder[2]='mag1'
myFolder[3]='mag2'

#myFolder[0]='ken2'

# Operations for each folder
# -------------------------------------------------------------------------------

for f in "${myFolder[@]}"
do

        find /srv/security_gz/$f/  -name "*.gz" -type f -mtime "+62" -exec rm  {} \;


done

